// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk7MZ9JMr9xv9ZezNGHNAmFW8CUoVRag4',
    appId: '1:503644935295:web:6bff599e1bfd1bd7fd9b4a',
    messagingSenderId: '503644935295',
    projectId: 'g-p-jofix',
    authDomain: 'g-p-jofix.firebaseapp.com',
    storageBucket: 'g-p-jofix.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh0F2FtcQSOGod0Bh6XwT_Z6LKgUrOSME',
    appId: '1:503644935295:android:e1414c490b5cd855fd9b4a',
    messagingSenderId: '503644935295',
    projectId: 'g-p-jofix',
    storageBucket: 'g-p-jofix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZxA-gUcZDX0ePPEKKvlzb_qgG8eKGMyA',
    appId: '1:503644935295:ios:b077075efd514629fd9b4a',
    messagingSenderId: '503644935295',
    projectId: 'g-p-jofix',
    storageBucket: 'g-p-jofix.firebasestorage.app',
    iosBundleId: 'com.example.amjad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZxA-gUcZDX0ePPEKKvlzb_qgG8eKGMyA',
    appId: '1:503644935295:ios:b077075efd514629fd9b4a',
    messagingSenderId: '503644935295',
    projectId: 'g-p-jofix',
    storageBucket: 'g-p-jofix.firebasestorage.app',
    iosBundleId: 'com.example.amjad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk7MZ9JMr9xv9ZezNGHNAmFW8CUoVRag4',
    appId: '1:503644935295:web:28b29fce432cd813fd9b4a',
    messagingSenderId: '503644935295',
    projectId: 'g-p-jofix',
    authDomain: 'g-p-jofix.firebaseapp.com',
    storageBucket: 'g-p-jofix.firebasestorage.app',
  );
}
